function DiffDistance = getDiffCurvePointDistance( Point, CurvePoint, Distance, DiffCurvePoint )
    DiffDistance = ( 1 / Distance ) * ( ...
        + ( CurvePoint(1) - Point(1) ) * DiffCurvePoint(1) ...
        + ( CurvePoint(2) - Point(2) ) * DiffCurvePoint(2) ...
    );
end