function DdiffDistance = getDdiffCurvePointDistance( Point, CurvePoint, Distance, DiffCurvePoint, DiffDistance, DdiffCurvePoint )
    DdiffDistance = ( 1 / Distance ) * ( ...
        - DiffDistance ...
        + ( CurvePoint(1) - Point(1) ) * DdiffCurvePoint(1) + DiffCurvePoint(1)^2 ...
        + ( CurvePoint(2) - Point(2) ) * DdiffCurvePoint(2) + DiffCurvePoint(2)^2 ...
    );
end